CREATE DATABASE IF NOT EXISTS 
patessrie;

USE patessrie;

CREATE TABLE IF NOT EXISTS ADMIN (
  ID_ADMIN INT NOT NULL PRIMARY KEY,
  NAME TEXT,
  EMAIL TEXT,
  MODE_PASSE TEXT,
  ROLE NUMERIC

);

CREATE TABLE IF NOT EXISTS CATEGORIES (
  ID_CATEGORIE INT NOT NULL PRIMARY KEY,
  NAME TEXT,
  DESCRIPTION TEXT
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
  ID_PRODUIT INT NOT NULL PRIMARY KEY,
  ID_CATEGORIE INT NOT NULL,
  NAME TEXT,
  DESCRIPTION TEXT,
  PRIX DECIMAL(10, 2),
  IMAGE_URL TEXT,
  FOREIGN KEY (ID_CATEGORIE) REFERENCES CATEGORIES(ID_CATEGORIE)
);

CREATE TABLE IF NOT EXISTS CLIENTS (
  ID_CLIENT INT NOT NULL PRIMARY KEY,
  NAME TEXT,
  PHONE VARCHAR(100),
  EMAIL TEXT,
  MODE_PASSE TEXT,
  LOCALISATION TEXT
);

CREATE TABLE IF NOT EXISTS COMMANDER (
  ID_PRODUIT INT NOT NULL,
  ID_CLIENT INT NOT NULL,
  DATE_DE_COMMANDE TIMESTAMP,
  SITUATION_DE_COMMANDE TEXT,
  SITUATION_DE_PAYMENT SMALLINT,
  PRIMARY KEY (ID_PRODUIT, ID_CLIENT),
  FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUCTS(ID_PRODUIT),
  FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTS(ID_CLIENT)
);

CREATE TABLE IF NOT EXISTS AJOUTER (
  ID_ADMIN INT NOT NULL,
  ID_PRODUIT INT NOT NULL,
  PRIMARY KEY (ID_ADMIN, ID_PRODUIT),
  FOREIGN KEY (ID_ADMIN) REFERENCES ADMIN(ID_ADMIN),
  FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUCTS(ID_PRODUIT)
);

CREATE TABLE IF NOT EXISTS OFFER_ADMIN (
  ID_OFFRE_ADMIN INT NOT NULL PRIMARY KEY,
  NOME_DE_OFFRE TEXT,
  DESCRIPTION_DE_OFFRE TEXT,
  OFFRE_PRIX DECIMAL(10, 2)
);

CREATE TABLE IF NOT EXISTS OFFERS_PERSONNALISEES (
  ID_ADMIN INT NOT NULL,
  ID_PRODUIT INT NOT NULL,
  ID_OFFRE_ADMIN INT NOT NULL,
  DATE_DE_OFFRE TIMESTAMP,
  PRIMARY KEY (ID_ADMIN, ID_PRODUIT, ID_OFFRE_ADMIN),
  FOREIGN KEY (ID_ADMIN) REFERENCES ADMIN(ID_ADMIN),
  FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUCTS(ID_PRODUIT),
  FOREIGN KEY (ID_OFFRE_ADMIN) REFERENCES OFFER_ADMIN(ID_OFFRE_ADMIN)
);

CREATE TABLE IF NOT EXISTS STORE (
  ID_STORE INT NOT NULL PRIMARY KEY,
  NAME TEXT,
  ADRESS TEXT,
  PHONE VARCHAR(100),
  EMAIL TEXT
);

CREATE TABLE IF NOT EXISTS PROPOSE (
  ID_PRODUIT INT NOT NULL,
  ID_STORE INT NOT NULL,
  DATE_DE_PROPOSE DATE,
  PRIMARY KEY (ID_PRODUIT, ID_STORE),
  FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUCTS(ID_PRODUIT),
  FOREIGN KEY (ID_STORE) REFERENCES STORE(ID_STORE)
);
